version: '2'
services:
  yukal-app:
    image: yukal
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://yukal-postgresql:5432/yukal
      - JHIPSTER_CACHE_REDIS_SERVER=redis://yukal-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://yukal-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  yukal-postgresql:
    extends:
      file: postgresql.yml
      service: yukal-postgresql
  yukal-redis:
    extends:
      file: redis.yml
      service: yukal-redis
